Updated update script, applied ValCher's LED patch

diff --git a/update b/update
--- a/update
+++ b/update
@@ -22,52 +22,72 @@ ask() { local q="$1"; local d=${2:-"n"}
 workdir=$(dirname $(realpath `dirname $0`)); err=0
 distro="linux-stable"
 current_tag="v4.14.32"
+color_no='\033[0m'
+color_fail='\033[0;31m'
+color_ok='\033[0;32m'
 echo "This script will pull sources from git and update Ubuntu-WRT."
-echo "The sources of $distro will be needed. You should clone them to $workdir folder. Current tag: $current_tag."
+echo "The sources of $distro will be needed. You should clone them to $workdir"
+echo "folder. Current tag: $current_tag."
 echo "Sources will be pulled within the parent directory: $workdir"
 if ! ask "Do you wish to continue?" "y"; then exit 0; fi
+
+# remove all $distro files
+echo "Backing up .config."
+cp "$workdir/ubuntu-wrt/$distro/.config" /tmp/config.backup
+echo -n "Removing current files... "
+rm -r "$workdir/ubuntu-wrt/$distro" > /dev/null 2>&1 &&\
+  echo -e "${color_ok}[OK]${color_no}" &&\
+  mkdir "$workdir/ubuntu-wrt/$distro" ||\
+  echo -e "${color_fail}[Failed]${color_no}"
+if ! cp /tmp/config.backup "$workdir/ubuntu-wrt/$distro/.config" || ! rm /tmp/config.backup; then
+  echo "Something went wrong when trying to fetch .config backup."
+  exit 1
+fi
 
 # mwlwifi
 cd "$workdir"; echo "Updating mwlwifi... "
 [ ! -d ./mwlwifi ] && git clone https://github.com/kaloz/mwlwifi.git
 if cd mwlwifi; then
   git pull; cd ..
-  if rm -rf ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi; then
-    cp -r mwlwifi ubuntu-wrt/$distro/drivers/net/wireless/marvell/
-    rm -rf ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/.git
-    mv -f ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/Makefile.kernel ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/Makefile
-    rm -rf ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/bin
-    if [ -d "$workdir/$distro" ]; then
-      distro_ok=true
-      cd "$workdir/$distro"
-      if [ "$current_tag" != "$(git describe --tags)" ]; then
-        git checkout tags/$current_tag || \
-          (echo "Changes not commited on $distro. Please commit changes."; exit 1)
+  [ ! -d "ubuntu-wrt/$distro/drivers/net/wireless/marvell" ] && mkdir -p "ubuntu-wrt/$distro/drivers/net/wireless/marvell"
+  cp -r mwlwifi ubuntu-wrt/$distro/drivers/net/wireless/marvell/
+  rm -rf ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/.git
+  mv -f ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/Makefile.kernel ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/Makefile
+  rm -rf ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/bin
+  if [ -d "$workdir/$distro" ]; then
+    distro_ok=true
+    cd "$workdir/$distro"
+    if git status | grep -q 'Changes not staged for commit'; then
+      echo "Changes not commited on $distro. Please commit or drop changes."
+      exit 2
+    fi
+    if [ "$current_tag" != "$(git describe --tags)" ]; then
+      if ! git checkout tags/$current_tag > /dev/null; then
+        echo "Changes not commited on $distro. Please commit or drop changes."
+        exit 1
       fi
-      cd "$workdir/ubuntu-wrt/$distro"
-      [ ! -d "firmware" ] && mkdir firmware
-      for f in 'drivers/net/wireless/marvell/Kconfig' 'drivers/net/wireless/marvell/Makefile' 'firmware/Makefile' 'arch/arm/boot/dts/armada-385-linksys.dtsi' 'arch/arm/boot/dts/armada-385-linksys-rango.dts'; do
-        [ -f "$workdir/$distro/$f" ] &&\
-          cp -f "$workdir/$distro/$f" "$f" ||\
-          echo "File $f is missing... "
-      done
-    else
-      echo "$distro folder missing. Could not fetch necessary files!"
-      exit 1
     fi
-    # Apply ValCher's patches
-    for f in 'https://raw.githubusercontent.com/ValCher1961/McDebian_WRT3200ACM/master/kernel-4.14.X/patch.mvdrv' 'https://raw.githubusercontent.com/ValCher1961/McDebian_WRT3200ACM/master/kernel-4.14.X/patch.nand-ecc'; do
-      wget -q "$f" -O - | cat - | patch -p1
-    done &&\
-      rm -rf firmware
-    if ask "Do you wish to apply ValCher's regfree patch?" "y"; then
-      echo "Applying patches to mwlwifi... "
-      for f in 'https://raw.githubusercontent.com/ValCher1961/McDebian_WRT3200ACM/master/kernel-4.14.X/patch.rango.dts' 'https://raw.githubusercontent.com/ValCher1961/McDebian_WRT3200ACM/master/kernel-4.14.X/patch.regfree'; do
-        wget -q "$f" -O - | cat - | patch -p1
-      done
-    fi
+    cd "$workdir/ubuntu-wrt/$distro"
+    for f in 'drivers/net/wireless/marvell/Kconfig' 'drivers/net/wireless/marvell/Makefile' 'firmware/Makefile' 'arch/arm/boot/dts/armada-385-linksys.dtsi' 'arch/arm/boot/dts/armada-385-linksys-rango.dts' 'drivers/leds/trigger/Kconfig' 'drivers/leds/trigger/ledtrig-netdev.c' 'drivers/leds/trigger/Makefile'; do
+      [ ! -d "$(dirname $f)" ] && mkdir -p "$(dirname $f)"
+      [ -f "$workdir/$distro/$f" ] &&\
+        cp -f "$workdir/$distro/$f" "$f" ||\
+        echo "File $f is missing... "
+    done
   else
-    echo "mwlwifi driver missing. Maybe not right branch?"
+    echo "$distro folder missing. Could not fetch necessary files!"
+    exit 1
+  fi
+  # Apply ValCher's patches
+  for p in 'https://raw.githubusercontent.com/ValCher1961/McDebian_WRT3200ACM/master/kernel-4.14.X/patch.mvdrv' 'https://raw.githubusercontent.com/ValCher1961/McDebian_WRT3200ACM/master/kernel-4.14.X/patch.nand-ecc' 'https://raw.githubusercontent.com/ValCher1961/McDebian_WRT3200ACM/master/kernel-4.14.X/patch.leds-net'; do
+    wget -q "$p" -O - | cat - | patch -p1
+  done &&\
+    rm -rf firmware
+  if ask "Do you wish to apply ValCher's regfree patch?" "y"; then
+    echo "Applying patches to mwlwifi... "
+    for f in 'https://raw.githubusercontent.com/ValCher1961/McDebian_WRT3200ACM/master/kernel-4.14.X/patch.rango.dts' 'https://raw.githubusercontent.com/ValCher1961/McDebian_WRT3200ACM/master/kernel-4.14.X/patch.regfree'; do
+      wget -q "$f" -O - | cat - | patch -p1
+    done
   fi
 else
   echo "Failed to clone mwlwifi."
@@ -84,12 +104,22 @@ else
   err=$((err+10))
 fi
 
-# cake
+# sch_cake
 cd "$workdir"; echo "Updating sch_cake... "
 [ ! -d ./sch_cake ] && git clone https://github.com/dtaht/sch_cake.git
 if cd sch_cake; then
   git pull; cd ..
+  [ ! -d "ubuntu-wrt/$distro/net/sched" ] && mkdir -p "ubuntu-wrt/$distro/net/sched"
   cp -f sch_cake/*.c sch_cake/*.h ubuntu-wrt/$distro/net/sched/
+  echo "Writing Kconfig and Makefile."
+  cd "$workdir/ubuntu-wrt/$distro"
+  for f in 'net/sched/Kconfig' 'net/sched/Makefile'; do
+    [ -f "$workdir/$distro/$f" ] &&\
+      cp -f "$workdir/$distro/$f" "$f" ||\
+      echo "File $f is missing... "
+  done
+  sed -i '/^obj-$(CONFIG_NET_SCH_PIE).*/a obj-$(CONFIG_NET_SCH_CAKE)	+= sch_cake.o' net/sched/Makefile
+  sed -i 's/^config NET_SCH_INGRESS$/config NET_SCH_CAKE\n\ttristate "Cake (Common Applications Kept Enhanced)"\n\t---help---\n\t  Cake is the rollup of 3 years of deployment experience of the htb + fq_codel.\n\nconfig NET_SCH_INGRESS/' net/sched/Kconfig
 else
   echo "Failed to clone sch_cake."
   err=$((err+100))
@@ -100,6 +130,7 @@ cd "$workdir"; echo "Updating wireless-regdb... "
 [ ! -d ./wireless-regdb ] && git clone git://git.kernel.org/pub/scm/linux/kernel/git/linville/wireless-regdb.git
 if cd wireless-regdb; then
   git pull; cd ..
+  [ ! -d "ubuntu-wrt/$distro/net/wireless" ] && mkdir -p "ubuntu-wrt/$distro/net/wireless"
   cp -f wireless-regdb/db.txt ubuntu-wrt/$distro/net/wireless/db.txt
 else
   echo "Failed to clone wireless-regdb."
